### ISSUE TITLE
How to set empty aliase for default_locale ?

### ISSUE THREAD

**Issue by webspilka** [tractorcow/silverstripe-fluent#109]
Hi 
my page has URL ru/about-us and en/about-us
I ned change it to /about-us and en/about-us (remove aliases from default locale)
I have next config
```
default_locale: ru_RU
  locales:
    - ru_RU
    - en_US
  aliases:
    ru_RU: 'ru'
    en_US: 'en'
```
if I change 
```
...
 aliases:
    ru_RU: ''
...
```
it not change URL to /about-us, it become ru-RU/about-us
