### ISSUE TITLE
Question: Custom routing scenario requiring Fluent support

### ISSUE THREAD

**Issue by leomeloxp** [tractorcow/silverstripe-fluent#212]
Is there a right way of custom routes to respect fluent URL style?

In *routes.yml* I have something like:

```yml
'video/Something/$ID!': 'VideoSomething_Controller'
'video': 'VideoIndex_Controller'
```
*Note:* These controllers extend `Page_Controller`

I would like to make it:

```yml
'en/video/Something/$ID!': 'VideoSomething_Controller'
'da/video/Something/$ID!': 'VideoSomething_Controller'
'en/video': 'VideoIndex_Controller'
'da/video': 'VideoIndex_Controller'
```

*Fluent.yml*:

```yml
---
Name: fluent
After: '#fluentconfig'
---
Fluent:
  default_locale: en_US
  locales:
    - en_US
    - da_DK
  aliases:
    en_US: en
    da_DK: da
---
Name: fluenti18n
After: '#fluenti18nconfig'
---
i18n:
  default_locale: en_US
```

When I try to access the endpoint for the translated routes I get a soft 404:

> Sorry, it seems you were trying to access a page that doesn't exist.
> Please check the spelling of the URL you were trying to access and try again.

Worth noting that the soft 404 copy changes for each locale url.

**Comment by tractorcow** [comment]
For custom controllers you can use a querystring argument to set the locale. If you omit a prefix / querystring, then it'll fall back to the session value (so whichever locale was last seen by the user).

If you like the locale prefix, then you can do something like this:


```yaml
Director:
  routes:
    'video/Something/$ID!':
      Controller: 'VideoSomething_Controller'
      l: 'en_NZ'
    da/'video/Something/$ID!':
      Controller: 'VideoSomething_Controller'
      l: 'da_DA'
    'video':
      Controller: 'VideoIndex_Controller'
      l: 'en_NZ'
    'da/video':
      Controller: 'VideoIndex_Controller'
      l: 'da_DA'
```

**Comment by tractorcow** [comment]
Closing since I guess I've answered your question. :)

**Comment by leomeloxp** [comment]
@tractorcow That did answer, but I still got a few issues. I couldn't get the `routes` heading to work but it worked with the usual `rules` heading (is this documented anywhere?).

This may be relevant: At first I was still running into soft 404's with the solution you gave. So I created a new yml section:

```yml
---
Name: mySiteVideoroutes
After: fluent/*
---
Director:
  rules:
    'video':
      Controller: 'VideoIndex_Controller'
      l: 'en_US'
    'en/video':
      Controller: 'VideoIndex_Controller'
      l: 'en_US'
    'da/video':
      Controller: 'VideoIndex_Controller'
      l: 'da_DK'
```

It seems to work fine now. Is there any documentation for the `l` option for these routes? I looked around Fluent's docs (before opening the issue) but couldn't find any mention of this.

Either way, thank you very much for the lightning fast response, just saved me a lot of grief 🙂👍
