### ISSUE TITLE
"New Page" vs "What the docs say"

### ISSUE THREAD

**Issue by phptek** [tractorcow/silverstripe-fluent#214]
**Setup:**
- PHP 5.6
- Framework + CMS 3.4 (Non CWP)
- Fluent 3.4.0

**fluent.yml:**

``` yml

---
Name: ss34fluentconfig
After: '#fluentconfig'

---
Fluent:
  default_locale: en_NZ
  locales:
    - en_NZ
    - fr_FR
  aliases:
    en_NZ: en
    fr_FR: fr
  field_include:
    - Title
    - MenuTitle
    - Content
  detect_locale: false
  force_domain: false

---
Name: ss34fluenti18nconfig
After: '#fluenti18nconfig'

---
i18n:
  default_locale: en_NZ
```

Re-reading the docs here: https://github.com/tractorcow/silverstripe-fluent/blob/master/docs/en/how-fluent-works.md#creating-translations

This needs to be made clearer:

> It's ideal, but not always necessary, to create a record in the default locale.

The problem is that it's not obvious what _should happen_ when a record is indeed created in a non-default locale.

Having tested Fluent 3.4.0 on SS 3.4, what happens for SiteTree objects created at the top level of the CMS' site tree, is that "New Page" appears for MenuTitle in the frontend main menu for the "EN" locale, and the expected French MenuTitle when in the "FR" locale.

IMO this should be documented perhaps with some tips as to how to work around it i.e. using `FluentFilteredLocale` or even an `augmentSQL()` workaround that checks for `MenuTitle === _t('CMSMain.NEWPAGE')`.

> If a record is NOT created in the default locale then the default value of that record will be the value last saved in any locale.

I'm either misunderstanding what this really means and its ramifications or it needs to be made clearer or there's a bug.

Given the scenario above, where "New Page" shows when I create a page in a non-default locale, then the documentation above is not accurate. What's _actually_ happening is that the default value for this record stays as the CMS' default "New Page" and _only_ the field(s) saved for the non-default locale, contain the expected content.
