### ISSUE TITLE
Fluent extension causes MySQL Errors with version >= 5.7.5

### ISSUE THREAD

**Issue by bummzack** [tractorcow/silverstripe-fluent#257]
The problem arises when the [`FluentExtension` uses `COALESCE`](https://github.com/tractorcow/silverstripe-fluent/blob/master/code/extensions/FluentExtension.php#L660) on colums that should be sorted.

Say you have a translatable DataObject `Article`, with a `Title` field and you want to sort by `Title`. It works in MySQL 5.6, but generates the following error on MySQL 5.7.13:

    Article::get()->sort('Title'); // using the localized column name doesn't help either

> Expression #1 of ORDER BY clause is not in SELECT list, references column 'Article.Title_en_US' which is not in SELECT list; this is incompatible with DISTINCT

I've looked around for the same issue and it seems to be caused by the following default setting: https://dev.mysql.com/doc/refman/5.7/en/sql-mode.html#sqlmode_only_full_group_by

Multiple sources state, that it can be fixed by setting `sql-mode` to a custom value that doesn't include `ONLY_FULL_GROUP_BY`, but I was unable to make it work locally. I'm assuming that a lot of people don't have full control over their mysql-server settings (depending on hosting-provider), so I guess this would be better fixed in code?

The only workaround so far seems to be to disable the coalescing of fields, by setting the sortable field to be nullable. Eg.

```yml
Article:
  extensions:
    - FluentExtension
  translate:
    - Title
    - Content
nullable_fields:
  - Title # adding this makes the error go away!
```
