### ISSUE TITLE
Localised File and Folder Support

### ISSUE THREAD

**Issue by chillu** [tractorcow/silverstripe-fluent#324]
Add the following config:

```yml
SilverStripe\Assets\File:
  extensions:
    - 'TractorCow\Fluent\Extension\FluentExtension'
  translate:
    - Title
```

Observed bugs:

 * Uploading files in `admin/assets` fails, see https://gist.github.com/chillu/d44d00b7fa984ec8fb65044b675194ae
 * Editing editing files in `admin/assets` fails (500 error without content)
 * Creating a folder fails in `admin/assets` fails (500 error without content)
 * Listing files in other languages can't be tested because of the above. It should pass through the `l` query param through to the `files` GraphQL query, rather than relying on session state.
