### ISSUE TITLE
siteconfig not translating

### ISSUE THREAD

**Issue by guyvanbael** [tractorcow/silverstripe-fluent#333]
I have a siteconfigextenstion which extends siteconfig, but none of the fields get localised.
here's my yml

```yaml
---
Name: myproject
---
SilverStripe\Core\Manifest\ModuleManifest:
  project: mysite
SilverStripe\SiteConfig\SiteConfig:
  extensions:
    - pena\entelec\SiteConfigExtension 
    - TractorCow\Fluent\Extension\FluentFilteredExtension
SilverStripe\CMS\Model\SiteTree:
  extensions:
    - TractorCow\Fluent\Extension\FluentFilteredExtension
SilverStripe\Assets\File:
  extensions:
    - FileExtension
pena\entelec\SiteConfigExtension:
  extensions:
    - TractorCow\Fluent\Extension\FluentFilteredExtension
  translate:
    - linkToContactPageID
    - FacebookLink
    - LinkedInLink
    - YoutubeLink
    - Emailadres
                
```
