### ISSUE TITLE
Language per Domain, without Locals in URL, strange behaviour

### ISSUE THREAD

**Issue by RoyalPulp** [tractorcow/silverstripe-fluent#95]
Hi Damian!

This weekend we launched the website for a client. 
The main language is german, second language english
One Domain per locale 
http://www.breimann-bruun.de
http://www.breimann-bruun.com

I was very happy when I saw, that the latest Fluent version is able to strip the locale from the URL Segment.

In Chrome Browser everything works fine.
But in Firefox and IE I get a strange behaviour with the english version:
- 404 Error when I open URLs
- AJAX Calls return german items
- when I open URLs with the /en/ it seems to work

``` yml

---
Name: myfluentconfig
After: '#fluentconfig'

---
Fluent:
  detect_locale: false
  force_domain: true
  remember_locale: false
  default_locale: de_DE
  locales:
    - de_DE
    - en_US
  aliases:
    de_DE: de
    en_US: en
  domains:
    www.breimann-bruun.de:
      locales:
        - de_DE
      default_locale: de_DE
    www.breimann-bruun.com:
      locales:
        - en_US
      default_locale: en_US

---
Name: myfluenti18nconfig
After: '#fluenti18nconfig'

---
i18n:
  default_locale: de_DE
```

Greetings,
Hendrik
